### PR TITLE
Add --json-output option for diff and push commands

### PR DESCRIPTION
**Pull request by Santiclause**
The motivation for this flag is to leverage skeema as a component utility of a larger automated workflow, and utilize the information that skeema is able to determine (specifically, in my case, it's for Vitess). Trying to use the alter-wrapper and ddl-wrapper options in this case is fairly clumsy - I'd have to, what, make the ddl-wrapper an `echo` that spits out manually hand-cranked JSON, or something? 🤷

Example output:

```
skeema diff localhost --json-output
2020-10-15 14:36:58 [INFO]  Generating diff of 127.0.0.1:3306 test-schema vs /Users/santiclause/dev/schemas/test-schema/*.sql
{"CLASS":"DATABASE","CLAUSES":"","CONNOPTS":"innodb_strict_mode=0,sql_mode='ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'","DDL":"CREATE DATABASE `test-schema` CHARACTER SET latin1 COLLATE latin1_swedish_ci","DIRNAME":"test-schema","DIRPATH":"/Users/santiclause/dev/schemas/test-schema","ENVIRONMENT":"localhost","HOST":"127.0.0.1","NAME":"test-schema","PORT":"3306","SCHEMA":"","SIZE":"0","SOCKET":"","TABLE":"","TYPE":"CREATE","USER":"root"}
{"CLASS":"TABLE","CLAUSES":"(\n  `bar` varchar(50) NOT NULL,\n  PRIMARY KEY (`bar`)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1","CONNOPTS":"innodb_strict_mode=0,sql_mode='ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'","DDL":"CREATE TABLE `foo` (\n  `bar` varchar(50) NOT NULL,\n  PRIMARY KEY (`bar`)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1","DIRNAME":"test-schema","DIRPATH":"/Users/santiclause/dev/schemas/test-schema","ENVIRONMENT":"localhost","HOST":"127.0.0.1","NAME":"foo","PORT":"3306","SCHEMA":"test-schema","SIZE":"0","SOCKET":"","TABLE":"foo","TYPE":"CREATE","USER":"root"}
2020-10-15 14:36:58 [INFO]  127.0.0.1:3306 test-schema: diff complete
```

### CODE REVIEW

**Comment by evanelias** [comment]
Thank you for the pull request. Can you describe your use-case in greater detail please? Generally I'd prefer to have discussion on a feature request issue before a PR is opened, to ensure there isn't already an existing way in Skeema to achieve the same result. Unfortunately I'm unable to dedicate very much time to open source (including code review) for the foreseeable future, so I need to prioritize based on changes that are beneficial for the largest number of users.

If/when this does move forwards, please be sure to fix the failing integration test (there's at least one failure in the applier subpackage) as well as add new test coverage for the new code. A full dev tutorial is still pending but there's a brief guide on the CI/test setup [in this comment](https://github.com/skeema/skeema/issues/132#issuecomment-640250594). Thanks again.

**Comment by evanelias** [comment]
Thank you for adding a test, but to reiterate and clarify: I would like to have a conversation about the full use-case here *first*, before even considering this PR in any way. As-is, I do not have enough information to evaluate the purpose of this change.  In particular, I would like to understand:

* What is your larger workflow doing?
* How does Skeema fit into it? Are you only using `skeema diff` and no other aspect of Skeema?
* How does Vitess fit into the picture?
* Why do you need to pass *all* of the variables from Skeema, in JSON format? Which variables are you actually using, and what prevents use of a `alter-wrapper` / `ddl-wrapper` command-line using just those variables?

**Comment by Santiclause** [comment]
The general picture of the workflow is that I query the Vitess `vtgate` for a list of shards, then run `skeema` against each shard individually. As part of the workflow, I use both `diff` and `push`, for various reasons: `diff` is used to generate individual `gh-ost` k8s Jobs for each alter table statement, and `push` is used when directly creating or dropping tables (with `alter-wrapper` set to "`true`", i.e the literal `true` binary, to effectively disable alters). `diff` is also used to show expected changes, per shard.

To be clear, this is all happening automatically - I have another program that manages all of this.

Currently, I use the `TYPE`, `SCHEMA`, `TABLE`, `CLAUSES`, `DDL`, and `SIZE` variables.

Moreover, I actually use the json-output for the `push` command as well; whenever I need to create a table that has a corresponding Vitess sequence, extra stuff needs to happen to ensure that the sequence exists.

**Comment by evanelias** [comment]
Thank you for the context. I believe you could accomplish this using existing features in Skeema:

* Use [host-wrapper](https://github.com/skeema/skeema/blob/main/doc/options.md#host-wrapper) to map directories to multiple Vitess shards
* For diffs, continue to use standard `skeema diff` for examining changes per shard. For a nicer inline-in-PR flow, try [Skeema Cloud Linter](https://www.skeema.io/cloud/), which provides monetary support for hopefully resuming Skeema open source development in the near future.
* For pushes, write a custom script/program and use this for [ddl-wrapper](https://github.com/skeema/skeema/blob/main/doc/options.md#ddl-wrapper). Pass it the variables you need on the command-line. Use this same script for all pushes; it should be one unified entry point to perform whatever conditional logic you need re: gh-ost invocations, different handling based on `{TYPE}` for alter vs create/drop, Vitess sequence handling, etc.

I believe this would be cleaner than what you’ve described. Having `skeema diff` create gh-ost jobs sounds risky (the intention of `skeema diff` is that it’s a dry-run with no side effects and no invocation of external scripts), and setting alter-wrapper to `true` seems confusing/hacky.

Regarding creation of Vitess sequences: since Vitess contains a SQL parser, I would imagine there could be a cleaner Vitess-native way to do this by parsing the DDL, without needing Skeema’s variables?

**Comment by Santiclause** [comment]
>     * Use [host-wrapper](https://github.com/skeema/skeema/blob/main/doc/options.md#host-wrapper) to map directories to multiple Vitess shards
This isn't cleaner, it just changes where the logic happens ("above" skeema versus "below" skeema). I'm inclined towards the logic happening upstream from skeema, because I also have other non-skeema-related things that I do with this information.

>     * For pushes, write a custom script/program and use this for [ddl-wrapper](https://github.com/skeema/skeema/blob/main/doc/options.md#ddl-wrapper). Pass it the variables you need on the command-line. Use this same script for all pushes; it should be one unified entry point to perform whatever conditional logic you need re: gh-ost invocations, different handling based on `{TYPE}` for alter vs create/drop, Vitess sequence handling, etc.
Again, this is just reversing the location of where all the logic happens. Why should skeema always be the parent program? Additionally, this would involve slightly more work, as it means I can't rely on default `skeema push` behaviour to actually perform non-alter DDLs, and would have to implement that myself. Just a small nit, because that's not particularly difficult.

> Having `skeema diff` create gh-ost jobs sounds risky (the intention of `skeema diff` is that it’s a dry-run with no side effects and no invocation of external scripts)
`skeema diff` isn't creating or doing anything - _my program_ is creating `gh-ost` Jobs. `skeema diff` is just used to inform what those Jobs do.

> setting alter-wrapper to `true` seems confusing/hacky.
Don't disagree, but there's no way to exclude alters other than setting a no-op alter-wrapper, and it's not all that confusing given that I explicitly spell out that that's what it's doing in a comment on the line immediately prior in my code.

> Regarding creation of Vitess sequences: since Vitess contains a SQL parser, I would imagine there could be a cleaner Vitess-native way to do this by parsing the DDL, without needing Skeema’s variables?
Yes, I could just parse the DDL myself, but at that point, why am I using skeema? skeema has literally every piece of information that I need, easily available. I'm not a fan of reinventing wheels, especially with such a robust extant solution as skeema.

**Comment by evanelias** [comment]
> This isn't cleaner, it just changes where the logic happens ("above" skeema versus "below" skeema). I'm inclined towards the logic happening upstream from skeema, because I also have other non-skeema-related things that I do with this information.

Skeema is designed to map directories to databases. Using `host-wrapper` enables this to work in a sharded manner, generically. You are free to use some other mechanism, but you'll be fighting against the happy path of a core concept in Skeema's design. 

> Again, this is just reversing the location of where all the logic happens. Why should skeema always be the parent program? 

Skeema is a schema management tool. The purpose of `skeema push` is to perform schema changes. It shouldn't be a surprise that Skeema should be the parent program for performing a schema change. It's the entire purpose of the system. `ddl-wrapper` just allows you do plug in your own logic for performing the actual schema change.

> I'm not a fan of reinventing wheels

Neither am I, and this PR -- which you submitted without any prior conversation or feature request -- reinvents wheels that Skeema can already do, just to satisfy your company's very specific workflow.

Skeema is open source, and you're of course free to fork or clone it for your internal purposes, but I'm disinclined to merge this PR so far. I would like to see if other users have similar needs that aren't handled by the existing features, and if so, figure out the best generic way of solving those needs. There's other JSON-related functionality being considered, so this may fit in better with that, albeit in a different form (I wasn't planning on having diff JSON line up 1:1 with ddl-wrapper variables, as the two serve different purposes).

**Comment by evanelias** [comment]
To summarize a discussion I had with PlanetScale staffers, Vitess's operation model does not allow Skeema to talk directly to MySQL, which completely prevents idiomatic usage of Skeema in its current form.

As Skeema is a bootstrapped project, and I do not have the time or energy to support non-idiomatic use-cases, I will be closing any PRs or issues for Vitess-related use-cases. I hope that this situation changes in the future.

**Pull request closed without merging**
